module.exports.APIEnum = {
  AUTH: "auth",
  CATEGORY: "category",
  FAVORITE: "favorite",
  ITEM: "item",
  PRODUCT: "product",
  SEARCH_HISTORY: "search-history",
  SUB_CATEGORY: "sub-category",
  TYPE_OF_SERVICE: "type-of-service",
  PRICE_INDICATED: "price-indicated",
  PLACE_OF_RENDERING: "place-of-rendering",
  RATE: "rate",
  FOLLOW: "follow",
  REPORT: "report",
  SPECIFICATION: "specification",
};
